version: '3.7'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: gaff
    volumes:
    - "./initdb/:/docker-entrypoint-initdb.d"
    - db_volume:/var/lib/mysql
  www:
    depends_on:
    - db
    build: ./Dockerfile
    volumes:
    - "./phpdir/:/var/www/html"
    ports:
    - 80:80
    - 443:443
volumes:
  db_volume:
