version: '3.7'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: gaff
    volumes:
    - "./db/:/docker-entrypoint-initdb.d"
    restart:
      always
  apache:
    build: ./apache
    volumes:
    - "./apache/:/var/www/html"
    ports:
    - 8080:80
  nginx:
    build: ./nginx
    ports:
    - 8081:80
    volumes:
      - "./nginx/:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
